pekko {
  loglevel = "INFO"

  actor {
    provider = "cluster"
    serialization-bindings {
        "com.messenger.messages.CborSerializable" = jackson-cbor
    }
  }

  remote.artery {
    canonical {
      hostname = "127.0.0.1"
      hostname = ${?K8S_POD_IP}

      bind-hostname = "0.0.0.0"
      port = 25520
    }

    bind {
      hostname = "0.0.0.0"
      port = 25520
    }
  }

  cluster {
    seed-nodes = []
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"

    sharding {
      state-store-mode = ddata
    }
  }

  discovery {
    kubernetes-api {
      pod-label-selector = "app=%s"
    }
  }

  management {
    http {
      hostname = "127.0.0.1"
      hostname = ${?K8S_POD_IP}

      bind-hostname = "0.0.0.0"
      port = 8558

      route-providers-read-only = false
    }

    cluster.bootstrap {
      contact-point-discovery {
        discovery-method = kubernetes-api
        service-name = "messenger-cluster"
        required-contact-point-nr = 2
      }
    }
  }
}
