include "pekko-cluster-base"

pekko.cluster.roles = ["auth"]

jwt {
  secret = "development-only"
  secret = ${?JWT_SECRET}
  life_time = 86400000
  life_time = ${?JWT_LIFE_TIME}
}

jdbc-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 10
  }
  throughput = 1
}
database {
  postgres {
    host = "127.0.0.1"
    host = ${?DB_HOST}

    port = 5432

    db_name = ${DB_NAME}

    user = "messenger"
    user = ${?DB_USER}

    password = "password"
    password = ${?DB_PASSWORD}

    hikari {
        poolName = "MennsengerAuthHikariPool"
        maximumPoolSize = 10
        minimumIdle = 2
        connectionTimeout = 30000
        idleTimeout = 600000
        maxLifetime = 1800000
    }
  }
}