include "pekko-cluster-base"

pekko {
  http.server {
    idle-timeout = infinite

    websocket {
      periodic-keep-alive-mode = ping
      periodic-keep-alive-interval = 20s
    }
  }

  cluster {
    roles = ["gateway"]
  }
}

