include "pekko-cluster-base"

pekko {
  cluster.roles = ["chat-core"]

  persistence {
    journal.plugin = "pekko.persistence.cassandra.journal"
    snapshot-store.plugin = "pekko.persistence.cassandra.snapshot"

    cassandra {
      journal {
        keyspace-autocreate = true
        tables-autocreate = true
      }
      snapshot {
        keyspace-autocreate = true
        tables-autocreate = true
      }
    }
  }
}

datastax-java-driver {
  basic.contact-points = ["127.0.0.1:9042"]
  basic.contact-points = [${?CASSANDRA_CONTACT_POINTS}]
  basic.load-balancing-policy.local-datacenter = "datacenter1"
}